### PR TITLE
#166841032 view reading stat

### PR DESCRIPTION
**Pull request by Alpha1202**
[Finishes ]

#### What does this PR do?
- User can see his articles views and stats

#### Description of Task to be completed?
- add read stat
- add views column to article table
- add read column to article table
- add readRatio column to article table

#### How should this be manually tested?
- Cloning this repo , RUN npm run start:dev

- Using postman , go to this endpoint api/v1/auth/login to generate a token

- then go to this endpoint api/v1/stats 

#### Any background context you want to provide?

- A logged in/authenticated user should be to view his stat

#### What are the relevant pivotal tracker stories?
- [#166841032](https://www.pivotaltracker.com/story/show/166841032)

#### Screenshots (if appropriate)
- 
Screenshot 2019-07-17 at 9 36 15 PM

#### Questions:
- N/A

### CODE REVIEW

**Review by chokonaira — COMMENTED** [review]
Hey Nzube, I have gone through your file changes and I can't find any test case, what is wrong? your file changes are so much, does this mean you have been tampering with files you don't have business with?

**Review by Alpha1202 — COMMENTED** [review]
Thank you so much, Henry, for the observation. You are very keen and meticulous and it is good. The files changes were due to the fact that getArticle method was not existing as at the time I implemented this task so I had to mock the method because it was blocking my task. Also, Test for getting an article was written alongside the get Article by slug implementation. Nevertheless, I accept your feedback and will appreciate it if you can be specific what the actions you recommend I should take.

**Comment by chokonaira** [comment]
> Thank you so much, Henry, for the observation. You are very keen and meticulous and it is good. The files changes were due to the fact that getArticle method was not existing as at the time I implemented this task so I had to mock the method because it was blocking my task. Also, Test for getting an article was written alongside the get Article by slug implementation. Nevertheless, I accept your feedback and will appreciate it if you can be specific what the actions you recommend I should take.

**Review by Cavdy — APPROVED** [review]

**Review by chokonaira — APPROVED** [review]

**Review by codeBlock-1984 — APPROVED** [review]
Great job @Alpha1202.

**Pull request merged**
