### PR TITLE
#166841000 Integrate HoundCI with a badge in ReadMe

### PR DESCRIPTION
**Pull request by chokonaira**
**What does this PR do?**
Set up and integrate HoundCI with a badge in Readme

**Description of Task completed?**

- Add .hound.yml file

- Integrate CI tool to repo

- Add CI badge to ReadMe

**How should this be manually tested**
N/A

**Any background context you want to provide?**
N/A

**What are the relevant pivotal tracker stories?**
[#166841000](https://www.pivotaltracker.com/story/show/166841000)

**Screenshots (if appropriate)**
N/A

**Questions:**
N/A

### CODE REVIEW

**Review by phembarl — COMMENTED** [review]
Looks good to me

**Review by czarjulius — COMMENTED** [review]
Looks good to me

**Review by codeBlock-1984 — COMMENTED** [review]
Great job @chokonaira. Good to go.

**Review by czarjulius — APPROVED** [review]

**Review by codeBlock-1984 — APPROVED** [review]

**Review by Cavdy — APPROVED** [review]
All good

**Review by Alpha1202 — APPROVED** [review]
Looks good

**Pull request merged**
